### ISSUE TITLE
mac user - changed line 49 to elif useros == 'Darwin': (used == instead of is)

### ISSUE THREAD

**Issue by scraggo** [DavidMetcalfe/Chrome-Bookmarks-Parser#2]
I'd love to get this working for me on mac. I'm an intermediate Python person and can verify once I do some tests. This is the first issue I've found

**Comment by DavidMetcalfe** [comment]
@scraggo Thanks for the effort! You're certainly welcome to contribute. Ideally, you'd create a pull request with the code changes involved. Are you comfortable doing that?

**Comment by scraggo** [comment]
@DavidMetcalfe Glad to hear back - I would love to contribute! I'm having issues getting `subprocess.Popen(cmd)` to call up the parsing module. I'm thinking I'll take it out of the try/except block to see what error pops up. If that isn't fruitful, I might just try importing it as a module in the backup script. Any thoughts about that? Was this working well on Windows?

**Comment by DavidMetcalfe** [comment]
@scraggo I also just merged in a branch that should improve exception handling, with more information available. Maybe take a look at that as well.

As for Windows, it has worked perfectly in all my testing. :)

**Comment by DavidMetcalfe** [comment]
@scraggo The issue with subprocess.Popen() might relate to this: http://stackoverflow.com/a/13753041/563231 but I'm unable to verify on my end without Mac OS.

**Comment by scraggo** [comment]
How does `print("{}".format(e.message))` work? I got this error:
```
Traceback (most recent call last):
  File "...Chrome-Bookmarks-Parser-master/Chrome_Bookmarks_backup.py", line 98, in <module>
    print("{}".format(e.message))
AttributeError: 'FileNotFoundError' object has no attribute 'message'
```

Otherwise, I got it working (and it works really well) with a couple of small changes:
```
# Variable declarations
cmd = ['python', 'Chrome_Bookmarks_Parser.py']
    # Check if platform is Mac OS X.
    elif useros == 'Darwin':
        profilePath = os.path.normpath(os.path.join(
            userhome, 'Library/Application Support/Google/Chrome/Default')) 
            #removed the preceding /

```

I'm pretty much a beginner with git - so it'll take me some time to figure out how to do pull requests. Any favorite resources for learning git?

**Comment by DavidMetcalfe** [comment]
You can find more information on `str.format()` here: https://docs.python.org/3.4/library/stdtypes.html#str.format

Basically I'm assigning the Exception to `e` and while the exception appears to be assigned properly to the variable, it doesn't have a `.message` attribute. So it might be a better for me to just print out `e` instead. It's not an error I've been able to simulate up to now, so this entails a bit of trail blazing on your part, for which I apologize.

For Git, what I would recommend is using the GitHub website for doing your submissions for now. The Git Shell and GitHub Desktop can be cumbersome when you're first getting into it. You should be able to commit to Master from your clone, and then create a pull request back to mine with the proposed changes, all from the website. Can't really recommend any particular resource though, as I never found any great ones and mainly just had to stumble through it on my own.

**Comment by DavidMetcalfe** [comment]
Here's some mock code below to show the Exception logic I suspect is happening:

```
try:
 print(http.whatever)
except Exception as e:
  print(e)
  print(type(e))
  print(e.__dict__)
```
Note that the last print provides an empty dict for the object. So I should be able to fix it simply by swapping `e.message` with `e`.

**Comment by DavidMetcalfe** [comment]
@scraggo I hadn't heard back, so I tested what changes I could, and committed the rest. Thanks again for the help!
